#!/bin/bash
set -e

# Get the directory of the script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="${SCRIPT_DIR}/.."
WORK_DIR="${ROOT_DIR}/_work/zetasql"
PATCHES_DIR="${ROOT_DIR}/patches"
BAZEL_PATCH_FILE="${ROOT_DIR}/patches/patches.bzl"

# Read ZETASQL_VERSION
source "${ROOT_DIR}/ZETASQL_VERSION"

if [ ! -d "$WORK_DIR" ]; then
    echo "Error: Work directory $WORK_DIR does not exist. Run setup_dev.sh first."
    exit 1
fi

cd "$WORK_DIR"

# Verify we are ahead of the base commit
if [ -z "$(git log $COMMIT_HASH..HEAD --oneline)" ]; then
    echo "No new commits found since $COMMIT_HASH."
    echo "Make sure you have committed your changes in $WORK_DIR."
    exit 0
fi

echo "Exporting patches from $WORK_DIR..."

# Clean old patches
rm -f "$PATCHES_DIR"/*.patch

# Generate new patches
# --start-number 1 ensures patches start with 0001
git format-patch "$COMMIT_HASH" -o "$PATCHES_DIR" --start-number 1

echo "Patches exported to $PATCHES_DIR"

# Update Bazel patch list
echo "Updating $BAZEL_PATCH_FILE..."

cat > "$BAZEL_PATCH_FILE" <<EOF
# This file is auto-generated by scripts/export_patches.sh
# Do not edit directly.

PATCHES = [
EOF

for patch in "$PATCHES_DIR"/*.patch; do
    filename=$(basename "$patch")
    echo "    \"//patches:$filename\"," >> "$BAZEL_PATCH_FILE"
done

cat >> "$BAZEL_PATCH_FILE" <<EOF
]
EOF

echo "Done!"
